export const INITIAL_BILLBOARDS = [
  {
    id: 'bb-01',
    title: 'S.G. Highway Digital Unipole',
    city: 'Ahmedabad',
    location: 'Near Iscon Cross Road, S.G. Highway',
    lat: 23.0269,
    lng: 72.5074,
    size: '30x15 ft',
    price: 75000,
    availability: 'Available',
    visibilityScore: 94,
    dailyTraffic: 145000,
    areaType: 'Highway',
    audienceType: 'Professionals & Shoppers',
    bestTiming: '08:00 AM - 11:00 PM',
    ownerName: 'Apex Media Corp',
    ownerContact: '+91 98765 43210',
    image: 'https://images.unsplash.com/photo-1541535650810-10d26f5c2ab3?auto=format&fit=crop&w=800&q=80',
    description: 'Ultra-bright LED screen on the busiest commercial highway in Gujarat. Outstanding visibility for retail, automobiles, and real estate.',
    reviews: 14,
    bookingCount: 42
  },
  {
    id: 'bb-02',
    title: 'Juhu Circle Premium Hoarding',
    city: 'Mumbai',
    location: 'Opposite Juhu Beach, Juhu Circle',
    lat: 19.1084,
    lng: 72.8258,
    size: '50x25 ft',
    price: 250000,
    availability: 'Available',
    visibilityScore: 98,
    dailyTraffic: 190000,
    areaType: 'Market / Beach Front',
    audienceType: 'High-income Families & Youth',
    bestTiming: '05:00 PM - 02:00 AM',
    ownerName: 'Vanguard Media Group',
    ownerContact: '+91 99999 88888',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    description: 'Stunning billboard visible from all Juhu Circle exit points. Premium positioning targetting elite spenders and tourists visiting the beach.',
    reviews: 29,
    bookingCount: 88
  },
  {
    id: 'bb-03',
    title: 'Cyber Hub Entrance Mega Board',
    city: 'Delhi-NCR',
    location: 'DLF Cyber City Entrance, Gurgaon',
    lat: 28.4950,
    lng: 77.0896,
    size: '40x20 ft',
    price: 180000,
    availability: 'Available',
    visibilityScore: 96,
    dailyTraffic: 220000,
    areaType: 'IT Park / Commercial',
    audienceType: 'Corporate Employees & Techies',
    bestTiming: '09:00 AM - 09:00 PM',
    ownerName: 'Capital Out-of-Home',
    ownerContact: '+91 91234 56789',
    image: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=800&q=80',
    description: 'Giant hoarding positioned directly at the entrance of Gurgaon Cyber City. Ideal for B2B, premium gadgets, lifestyle brands, and banking.',
    reviews: 21,
    bookingCount: 56
  },
  {
    id: 'bb-04',
    title: 'Koramangala 80ft Road Junction',
    city: 'Bangalore',
    location: 'Koramangala 5th Block, 80ft Road',
    lat: 12.9348,
    lng: 77.6224,
    size: '30x10 ft',
    price: 90000,
    availability: 'Booked',
    nextAvailableDate: '2026-06-10',
    visibilityScore: 91,
    dailyTraffic: 110000,
    areaType: 'Market Area',
    audienceType: 'Techies, Foodies & College Students',
    bestTiming: '12:00 PM - 11:00 PM',
    ownerName: 'South Outdoor Media',
    ownerContact: '+91 97777 66666',
    image: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
    description: 'Perfect commercial location with long visual distance along the bustling foodie road. Heavy pedestrian and two-wheeler traffic.',
    reviews: 8,
    bookingCount: 31
  },
  {
    id: 'bb-05',
    title: 'FC Road Youth Central Unipole',
    city: 'Pune',
    location: 'Opposite Fergusson College Entrance',
    lat: 18.5244,
    lng: 73.8415,
    size: '20x10 ft',
    price: 45000,
    availability: 'Available',
    visibilityScore: 88,
    dailyTraffic: 85000,
    areaType: 'School / College Area',
    audienceType: 'Students & Young Professionals',
    bestTiming: '09:00 AM - 10:00 PM',
    ownerName: 'Sahyadri Billboards',
    ownerContact: '+91 88888 77777',
    image: 'https://images.unsplash.com/photo-1617396900799-f4ec2b43c7ae?auto=format&fit=crop&w=800&q=80',
    description: 'High frequency youth exposure billboard directly facing the primary hangouts on FC Road. Unbeatable for food chains, test preps, and clothing.',
    reviews: 12,
    bookingCount: 25
  },
  {
    id: 'bb-06',
    title: 'Gachibowli Ring Road Digital Wall',
    city: 'Hyderabad',
    location: 'Outer Ring Road, Gachibowli Junction',
    lat: 17.4483,
    lng: 78.3741,
    size: '45x22 ft',
    price: 150000,
    availability: 'Available',
    visibilityScore: 95,
    dailyTraffic: 175000,
    areaType: 'Highway / Commercial',
    audienceType: 'IT Professionals & Airport Commuters',
    bestTiming: '07:00 AM - 10:00 PM',
    ownerName: 'Deccan Signs Ltd',
    ownerContact: '+91 95555 44444',
    image: 'https://images.unsplash.com/photo-1572248522899-40d874feb91c?auto=format&fit=crop&w=800&q=80',
    description: 'Gigantic digital display screen targeting fast-moving traffic entering Hyderabad\'s high-tech IT corridor. Highly modern, vibrant LED.',
    reviews: 19,
    bookingCount: 67
  }
];

export const POSTER_TEMPLATES = [
  {
    id: 'tpl-1',
    name: 'Festival Special (Diwali)',
    category: 'Festive',
    bgStart: '#7c2d12',
    bgEnd: '#450a0a',
    titleText: 'HAPPY DIWALI',
    subtitleText: 'FLAT 50% OFF ON ALL ITEMS',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    tagline: 'Light up your home with premium collections!',
    sticker: '🪔'
  },
  {
    id: 'tpl-2',
    name: 'Grand Store Opening',
    category: 'Launch',
    bgStart: '#1e1b4b',
    bgEnd: '#311042',
    titleText: 'GRAND LAUNCH',
    subtitleText: 'WE ARE NOW OPEN IN YOUR CITY',
    accentColor: '#22d3ee',
    textColor: '#ffffff',
    tagline: 'Visit today for exclusive opening gifts!',
    sticker: '✨'
  },
  {
    id: 'tpl-3',
    name: 'Election / Political Campaign',
    category: 'Political',
    bgStart: '#ea580c',
    bgEnd: '#1e3a8a',
    titleText: 'VOTE FOR PROGRESS',
    subtitleText: 'LEADERSHIP WITH INTEGRITY',
    accentColor: '#ffffff',
    textColor: '#ffffff',
    tagline: 'Building a better future together. Choose Progress.',
    sticker: '🇮🇳'
  },
  {
    id: 'tpl-4',
    name: 'Mega Clearance Sale',
    category: 'Sales',
    bgStart: '#be123c',
    bgEnd: '#4c0519',
    titleText: 'MEGA SALE',
    subtitleText: 'LIMITED PERIOD OFFER',
    accentColor: '#facc15',
    textColor: '#ffffff',
    tagline: 'Shop online & in-stores before stocks run out!',
    sticker: '🔥'
  }
];

export const REVENUE_STATS = {
  bookingCommission: 12, // in percent
  premiumListingFee: 2500, // in INR
  posterDesignCharges: 999, // in INR
  printingChargesPerSqFt: 45 // in INR
};
